### ISSUE TITLE
Error in Exercise_3

### ISSUE THREAD

**Issue by aavash1** [mohammadzainabbas/SDM-Lab-2#21]
In sendMsg function, when I try to return Tuple2 Iterator, I get following errors:
1. If I don't cast the return type to **(Iterator<Tuple2<Object,Vertex>>),** I get  Type Mismatch error: cannot convert form hence I typecast it using the given form.
2. Once I use the typecast, I just get warning but if I run the program I get follwoing error:
22/05/12 10:41:55 ERROR Executor: Exception in task 2.0 in stage 4.0 (TID 26)
java.lang.ClassCastException: class scala.collection.convert.Wrappers$JIteratorWrapper cannot be cast to class java.util.Iterator (scala.collection.convert.Wrappers$JIteratorWrapper is in unnamed module of loader 'app'; java.util.Iterator is in module java.base of loader 'bootstrap')

Could you please check the given issue, and let me know

**Comment by mohammadzainabbas** [comment]
@aavash1 There isn't any error in Exercise 3. 

It seems like you didn't modify the code correctly. Please refer to the original documentation and need to carefully modify the return types for your use case.

**Comment by aavash1** [comment]
> @aavash1 There isn't any error in Exercise 3.
> 
> It seems like you didn't modify the code correctly. Please refer to the original documentation and need to carefully modify the return types for your use case.

Yeah thanks, It was import error, I imported wrong library but then I figured out the issue hence I closed the issue. thank you for your response
